debug = true
testing = true
secret_key = "${SECRET_KEY|c62a1dff97c2310face9645edc9c814a0e8829202f756de392ce415484bcec4e}"
identity_strategy = "uuid"
identity_type = "string"
event_processing = "sync"
command_processing = "sync"

[databases.default]
provider = "memory"

[test.databases.default]
provider = "postgresql"
database_uri = "postgresql://test_postgres:test_postgres@localhost:5432/test_postgres"

[production.databases.default]
provider = "postgresql"
database_uri = "postgresql://postgres:postgres@localhost:5432/postgres"

[databases.memory]
provider = "memory"

[brokers.default]
provider = "inline"

[production.brokers.default]
provider = "redis"
URI = "redis://127.0.0.1:6379/0"
IS_ASYNC = true

[test.brokers.default]
provider = "redis"
URI = "redis://127.0.0.1:6379/1"
IS_ASYNC = false

[caches.default]
provider = "memory"

[event_store]
provider = "memory"

[test.event_store]
provider = "message_db"
database_uri = "postgresql://message_store@localhost:5433/message_store"

[production.event_store]
provider = "message_db"
database_uri = "postgresql://message_store@localhost:5433/message_store"

[custom]
CHECKOUT_PERIOD = 60  # Days
HOLD_EXPIRY_DAYS = 7  # Days