debug = true
testing = true
secret_key = "${SECRET_KEY|c62a1dff97c2310face9645edc9c814a0e8829202f756de392ce415484bcec4e}"
identity_strategy = "uuid"
identity_type = "string"
event_processing = "sync"
command_processing = "sync"

[databases.default]
provider = "memory"

[databases.memory]
provider = "memory"

[brokers.default]
provider = "inline"

[caches.default]
provider = "memory"

[custom]
CHECKOUT_PERIOD = 60  # Days
HOLD_EXPIRY_DAYS = 7  # Days